#docker run --name h2h-postgres -e POSTGRES_PASSWORD=password -d -p 5432:5432 postgres:alpine
#docker ps
#docker port h2h-postgres
#docker exec -it b49c60628f18 bin/bash
#psql -U postgres
#CREATE DATABASE h2hdb;
#\c h2hdb
#\q
#exit

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/h2hdb
    username: postgres
    password: password
    pool-size: 30