CREATE TABLE h2h_user_profile (
    userId UUID NOT NULL PRIMARY KEY,
    givenName VARCHAR(100) NOT NULL,
    familyName VARCHAR(100) NOT NULL,
    passportId VARCHAR(30),
    passportName VARCHAR(200),
    passportNationality VARCHAR(200),
    mobilePhone VARCHAR(20) NOT NULL,
    homePhone VARCHAR(20),
    workPhone VARCHAR(20),
    address VARCHAR(100),
    country VARCHAR(50),
    state VARCHAR(50),
    zipcode VARCHAR(20),
    lastLogin TIMESTAMP,
    loginCount INTEGER,
    effectiveFromDate DATE,
    effectiveToDate DATE,
    isActive BOOLEAN,
    isAdmin BOOLEAN,
    knowUsFrom VARCHAR(100),
    liveInShanghai BOOLEAN,
    isStudent BOOLEAN,
    birth DATE,
    school VARCHAR(100),
    hasSchoolAccrediation BOOLEAN,
    speakChinese BOOLEAN
);